// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7ln6_nOD1DmpvymuhT6wpCzcH8SK4cI',
    appId: '1:830954847165:web:f00841d8812dfe294770d4',
    messagingSenderId: '830954847165',
    projectId: 'uml-project-1b77a',
    authDomain: 'uml-project-1b77a.firebaseapp.com',
    storageBucket: 'uml-project-1b77a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRul9797l6J3FY9qi-p9-QI9RG-RqHGD4',
    appId: '1:830954847165:android:1d5ee5cec3333f484770d4',
    messagingSenderId: '830954847165',
    projectId: 'uml-project-1b77a',
    storageBucket: 'uml-project-1b77a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMp5_yX5calOO8LRRIY3eMW-FbYJoVqEI',
    appId: '1:830954847165:ios:79ad991ba9e6733a4770d4',
    messagingSenderId: '830954847165',
    projectId: 'uml-project-1b77a',
    storageBucket: 'uml-project-1b77a.appspot.com',
    iosClientId: '830954847165-8qi3s17llk694ivvnsgv9dqs7j4ktaol.apps.googleusercontent.com',
    iosBundleId: 'com.example.umlProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMp5_yX5calOO8LRRIY3eMW-FbYJoVqEI',
    appId: '1:830954847165:ios:79ad991ba9e6733a4770d4',
    messagingSenderId: '830954847165',
    projectId: 'uml-project-1b77a',
    storageBucket: 'uml-project-1b77a.appspot.com',
    iosClientId: '830954847165-8qi3s17llk694ivvnsgv9dqs7j4ktaol.apps.googleusercontent.com',
    iosBundleId: 'com.example.umlProject',
  );
}
